sonar.projectKey=ghazy001_ai-test-automation-platform
sonar.organization=ghazy001
sonar.projectName=ai-test-automation-platform

sonar.sources=backend/src,frontend,ai-service/app
sonar.tests=backend/test,frontend,ai-service/tests

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/.venv/**,**/__pycache__/**,**/.pytest_cache/**,**/.ruff_cache/**,**/uploads/**,**/tmp/**,**/temp/**

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,ai-service/tests/**/*.py

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=ai-service/coverage.xml

sonar.sourceEncoding=UTF-8
