-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'USER_CREATED', 'USER_UPDATED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'PROFILE_UPDATED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_MEMBER_ADDED', 'PROJECT_MEMBER_REMOVED', 'WORK_ITEM_CREATED', 'WORK_ITEM_UPDATED', 'WORK_ITEM_DELETED', 'WORK_ITEM_IMPORTED_JIRA', 'WORK_ITEM_IMPORTED_SPEC_DOCUMENT', 'TEST_CASE_GENERATION_STARTED', 'TEST_CASE_GENERATION_COMPLETED', 'TEST_CASE_GENERATION_FAILED', 'TEST_CASE_APPROVED', 'TEST_CASE_DECLINED', 'TEST_CASE_EDITED', 'AUTOMATION_SCRIPT_GENERATION_STARTED', 'AUTOMATION_SCRIPT_GENERATION_COMPLETED', 'AUTOMATION_SCRIPT_GENERATION_FAILED', 'AUTOMATION_SCRIPT_APPROVED', 'AUTOMATION_SCRIPT_DECLINED', 'AUTOMATION_SCRIPT_EDITED', 'AUTOMATION_SCRIPT_REMOVED', 'AUTOMATION_SCRIPT_DOWNLOADED', 'SCRIPT_EXECUTION_STARTED', 'SCRIPT_EXECUTION_PASSED', 'SCRIPT_EXECUTION_FAILED', 'SCRIPT_EXECUTION_TIMED_OUT', 'SCRIPT_EXECUTION_CANCELED', 'DEFECT_REPORT_CREATED', 'DEFECT_REPORT_UPDATED', 'DEFECT_REPORT_PDF_DOWNLOADED', 'TEST_SUITE_REPORT_CREATED', 'TEST_SUITE_REPORT_PDF_DOWNLOADED', 'SCHEDULED_RUN_CREATED', 'SCHEDULED_RUN_UPDATED', 'SCHEDULED_RUN_PAUSED', 'SCHEDULED_RUN_RESUMED', 'SCHEDULED_RUN_DISABLED', 'ANALYTICS_QUESTION_ASKED');

-- CreateEnum
CREATE TYPE "AuditEntityType" AS ENUM ('AUTH', 'USER', 'PROJECT', 'PROJECT_MEMBER', 'WORK_ITEM', 'JIRA', 'SPEC_DOCUMENT', 'TEST_CASE', 'TEST_CASE_GENERATION', 'AUTOMATION_SCRIPT', 'AUTOMATION_SCRIPT_GENERATION', 'SCRIPT_EXECUTION', 'DEFECT_REPORT', 'TEST_SUITE_REPORT', 'SCHEDULED_TEST_RUN', 'ANALYTICS_ASSISTANT');

-- CreateEnum
CREATE TYPE "AuditSeverity" AS ENUM ('INFO', 'WARNING', 'CRITICAL');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "actorId" TEXT,
    "actorEmail" TEXT,
    "actorName" TEXT,
    "actorRole" "Role",
    "action" "AuditAction" NOT NULL,
    "entityType" "AuditEntityType" NOT NULL,
    "entityId" TEXT,
    "projectId" TEXT,
    "message" TEXT NOT NULL,
    "severity" "AuditSeverity" NOT NULL DEFAULT 'INFO',
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "success" BOOLEAN NOT NULL DEFAULT true,
    "before" JSONB,
    "after" JSONB,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");

-- CreateIndex
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");

-- CreateIndex
CREATE INDEX "AuditLog_entityType_idx" ON "AuditLog"("entityType");

-- CreateIndex
CREATE INDEX "AuditLog_entityId_idx" ON "AuditLog"("entityId");

-- CreateIndex
CREATE INDEX "AuditLog_projectId_idx" ON "AuditLog"("projectId");

-- CreateIndex
CREATE INDEX "AuditLog_severity_idx" ON "AuditLog"("severity");

-- CreateIndex
CREATE INDEX "AuditLog_success_idx" ON "AuditLog"("success");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
