import httpx

from app.core.config import get_settings
from app.providers.ollama_utils import extract_json_object
from app.schemas.page_inspection import PageInspectionResult
from app.schemas.script_generation import (
    AutomationFramework,
    GenerateAutomationScriptRequest,
    GeneratedAutomationScript,
)


OLLAMA_SCRIPT_SCHEMA = {
    "type": "object",
    "properties": {
        "fileName": {"type": "string"},
        "language": {"type": "string"},
        "code": {"type": "string"},
        "explanation": {"type": ["string", "null"]},
        "dependencies": {
            "type": "array",
            "items": {"type": "string"},
        },
        "setupNotes": {
            "type": "array",
            "items": {"type": "string"},
        },
        "selectorsUsed": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "purpose": {"type": "string"},
                    "selector": {"type": "string"},
                    "source": {"type": "string"},
                },
                "required": ["purpose", "selector", "source"],
            },
        },
        "warnings": {
            "type": "array",
            "items": {"type": "string"},
        },
    },
    "required": [
        "fileName",
        "language",
        "code",
        "explanation",
        "dependencies",
        "setupNotes",
        "selectorsUsed",
        "warnings",
    ],
}


class OllamaAutomationScriptProvider:
    provider_name = "ollama"

    def __init__(self) -> None:
        self.settings = get_settings()
        self.model_name = self.settings.ollama_model

    def generate(
        self,
        request: GenerateAutomationScriptRequest,
        page_inspection: PageInspectionResult,
    ) -> GeneratedAutomationScript:
        framework = request.generationContext.framework
        target_url = request.generationContext.targetUrl

        test_case = request.testCase
        title = str(test_case.get("title") or "Generated automation test")
        expected_result = str(test_case.get("expectedResult") or "")
        steps = test_case.get("steps") or []

        file_name, language, dependency, code = self._build_safe_script(
            framework=framework,
            title=title,
            target_url=target_url,
            expected_result=expected_result,
            steps=steps,
            page_inspection=page_inspection,
        )

        prompt = f"""
Return ONLY valid JSON.
Do not use markdown.
Do not include explanation outside JSON.
Do not include <think>.

You are generating one automation script.

Framework: {framework}
File name must be: {file_name}
Language must be: {language}
Dependency must include: {dependency}

Test title: {title}
Expected result: {expected_result}

Use this exact code as the script code value:
{code}

Return JSON with this exact structure:
{{
  "fileName": "{file_name}",
  "language": "{language}",
  "code": "PUT_THE_SCRIPT_CODE_HERE",
  "explanation": "Generated by local Ollama fallback model.",
  "dependencies": ["{dependency}"],
  "setupNotes": ["Set BASE_URL before running.", "Review selectors before approval."],
  "selectorsUsed": [],
  "warnings": ["Generated by local Ollama fallback model with reduced prompt."]
}}
""".strip()

        response = httpx.post(
            f"{self.settings.ollama_base_url}/api/generate",
            json={
                "model": self.model_name,
                "prompt": prompt,
                "stream": False,
                "format": OLLAMA_SCRIPT_SCHEMA,
                "think": False,
                "options": {
                    "temperature": self.settings.ollama_temperature,
                    "num_predict": min(self.settings.ollama_num_predict, 900),
                    "num_ctx": self.settings.ollama_num_ctx,
                },
                "keep_alive": "10m",
            },
            timeout=httpx.Timeout(
                connect=10.0,
                read=float(self.settings.ollama_timeout_seconds),
                write=10.0,
                pool=10.0,
            ),
        )

        response.raise_for_status()

        data = response.json()
        raw_content = data.get("response", "")

        parsed = extract_json_object(raw_content)

        # Safety normalization:
        # If the small local model returned placeholder code, replace it with the safe script.
        parsed["fileName"] = file_name
        parsed["language"] = language

        generated_code = str(parsed.get("code") or "").strip()

        if (
            not generated_code
            or "PUT_THE_SCRIPT_CODE_HERE" in generated_code
            or len(generated_code) < 80
        ):
            parsed["code"] = code

        parsed["dependencies"] = parsed.get("dependencies") or [dependency]
        parsed["setupNotes"] = parsed.get("setupNotes") or [
            "Set BASE_URL before running.",
            "Review selectors before approval.",
        ]
        parsed["selectorsUsed"] = parsed.get("selectorsUsed") or []
        parsed["warnings"] = parsed.get("warnings") or [
            "Generated by local Ollama fallback model with reduced prompt."
        ]

        return GeneratedAutomationScript.model_validate(parsed)

    def _build_safe_script(
        self,
        framework: AutomationFramework,
        title: str,
        target_url: str,
        expected_result: str,
        steps: list,
        page_inspection: PageInspectionResult,
    ) -> tuple[str, str, str, str]:
        base_name = self._safe_file_base(title)

        if framework == AutomationFramework.PLAYWRIGHT_TS:
            file_name = f"{base_name}.spec.ts"
            language = "typescript"
            dependency = "@playwright/test"
            code = f"""import {{ test, expect }} from '@playwright/test';

test('{self._escape_ts(title)}', async ({{ page }}) => {{
  await page.goto(process.env.BASE_URL ?? '{self._escape_ts(target_url)}');

  await expect(page).toHaveTitle(/.*/);

  // Local fallback generated a safe skeleton.
  // Review and adapt these steps:
{self._steps_as_ts_comments(steps)}

  // Expected result:
  // {self._comment(expected_result)}
}});
"""
            return file_name, language, dependency, code

        if framework == AutomationFramework.PLAYWRIGHT_PYTHON:
            file_name = f"{base_name}.py"
            language = "python"
            dependency = "playwright"
            function_name = base_name.replace("-", "_") or "generated_test"

            code = f"""import os
import re
from playwright.sync_api import Page, expect


def test_{function_name}(page: Page):
    page.goto(os.getenv("BASE_URL", "{target_url}"))

    expect(page).to_have_title(re.compile(".*"))

    # Local fallback generated a safe skeleton.
{self._steps_as_python_comments(steps)}

    # Expected result:
    # {self._comment(expected_result)}
"""
            return file_name, language, dependency, code

        if framework == AutomationFramework.CYPRESS_TS:
            file_name = f"{base_name}.cy.ts"
            language = "typescript"
            dependency = "cypress"

            code = f"""describe('{self._escape_ts(title)}', () => {{
  it('runs the approved test case', () => {{
    cy.visit(Cypress.env('BASE_URL') || '{self._escape_ts(target_url)}');

    cy.document().its('title').should('exist');

    // Local fallback generated a safe skeleton.
{self._steps_as_ts_comments(steps)}

    // Expected result:
    // {self._comment(expected_result)}
  }});
}});
"""
            return file_name, language, dependency, code

        file_name = "GeneratedTest.java"
        language = "java"
        dependency = "selenium-java"

        code = f"""import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GeneratedTest {{

    @Test
    public void generatedTest() {{
        WebDriver driver = new ChromeDriver();

        try {{
            String baseUrl = System.getenv().getOrDefault("BASE_URL", "{target_url}");
            driver.get(baseUrl);

            // Local fallback generated a safe skeleton.
{self._steps_as_java_comments(steps)}

            // Expected result:
            // {self._comment(expected_result)}
        }} finally {{
            driver.quit();
        }}
    }}
}}
"""
        return file_name, language, dependency, code

    def _safe_file_base(self, title: str) -> str:
        base = "".join(ch.lower() if ch.isalnum() else "-" for ch in title).strip("-")

        while "--" in base:
            base = base.replace("--", "-")

        return base or "generated-test"

    def _escape_ts(self, value: str) -> str:
        return str(value).replace("\\", "\\\\").replace("'", "\\'")

    def _comment(self, value: str) -> str:
        return str(value or "").replace("\n", "\n  // ")

    def _steps_as_ts_comments(self, steps: list) -> str:
        if not steps:
            return "  // No detailed steps were provided."

        lines = []

        for step in steps[:8]:
            if isinstance(step, dict):
                action = step.get("action", "")
                expected = step.get("expected", "")
                lines.append(f"  // Step: {self._comment(action)}")
                lines.append(f"  // Expected: {self._comment(expected)}")

        return "\n".join(lines) or "  // No detailed steps were provided."

    def _steps_as_python_comments(self, steps: list) -> str:
        if not steps:
            return "    # No detailed steps were provided."

        lines = []

        for step in steps[:8]:
            if isinstance(step, dict):
                action = step.get("action", "")
                expected = step.get("expected", "")
                lines.append(f"    # Step: {action}")
                lines.append(f"    # Expected: {expected}")

        return "\n".join(lines) or "    # No detailed steps were provided."

    def _steps_as_java_comments(self, steps: list) -> str:
        if not steps:
            return "            // No detailed steps were provided."

        lines = []

        for step in steps[:8]:
            if isinstance(step, dict):
                action = step.get("action", "")
                expected = step.get("expected", "")
                lines.append(f"            // Step: {action}")
                lines.append(f"            // Expected: {expected}")

        return "\n".join(lines) or "            // No detailed steps were provided."